apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-code-pvc
  namespace: web-batik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Ukuran untuk source code
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads-pvc
  namespace: web-batik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Ukuran lebih besar untuk file upload
