version: "3.7"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: batik-api-web

    command: gunicorn src.app.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000

    env_file:
      - ./src/.env

    depends_on:
      - db
      - redis

    expose:
      - "8000"

    networks:
      - backend

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend"

      - "traefik.http.routers.batik-api.rule=Host(`batik.umm.ac.id`) && PathPrefix(`/api`)"
      - "traefik.http.routers.batik-api.entrypoints=websecure"
      - "traefik.http.routers.batik-api.tls=true"

      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.batik-api.middlewares=api-strip"

      - "traefik.http.services.batik-api.loadbalancer.server.port=8000"


  worker:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: batik-api-worker

    command: arq app.core.worker.settings.WorkerSettings

    env_file:
      - ./src/.env

    depends_on:
      - db
      - redis

    networks:
      - backend


  db:
    image: postgres:13

    container_name: batik-api-db

    env_file:
      - ./src/.env

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - backend


  redis:
    image: redis:alpine

    container_name: batik-api-redis

    volumes:
      - redis-data:/data

    networks:
      - backend


volumes:
  postgres-data:
  redis-data:


networks:
  backend:
    driver: bridge