"""Initial migration with all ERD models

Revision ID: d1ffbce560e2
Revises:
Create Date: 2025-11-22 13:11:37.570343

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d1ffbce560e2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_is_deleted"), table_name="user")
    op.drop_index(op.f("ix_user_tier_id"), table_name="user")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_token_blacklist_token"), table_name="token_blacklist")
    op.drop_table("token_blacklist")
    op.alter_column("post", "created_by_user_id", existing_type=sa.INTEGER(), type_=sa.UUID(), existing_nullable=False)
    op.create_unique_constraint(None, "post", ["id"])
    op.drop_constraint(op.f("post_created_by_user_id_fkey"), "post", type_="foreignkey")
    op.create_foreign_key(None, "post", "users", ["created_by_user_id"], ["id"])
    op.create_unique_constraint(None, "rate_limit", ["id"])
    op.create_unique_constraint(None, "tier", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tier", type_="unique")
    op.drop_constraint(None, "rate_limit", type_="unique")
    op.drop_constraint(None, "post", type_="foreignkey")
    op.create_foreign_key(op.f("post_created_by_user_id_fkey"), "post", "user", ["created_by_user_id"], ["id"])
    op.drop_constraint(None, "post", type_="unique")
    op.alter_column("post", "created_by_user_id", existing_type=sa.UUID(), type_=sa.INTEGER(), existing_nullable=False)
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("token_blacklist_pkey")),
    )
    op.create_index(op.f("ix_token_blacklist_token"), "token_blacklist", ["token"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("username", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("profile_image_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("tier_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["tier_id"], ["tier.id"], name=op.f("user_tier_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
        sa.UniqueConstraint(
            "uuid", name=op.f("user_uuid_key"), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_index(op.f("ix_user_tier_id"), "user", ["tier_id"], unique=False)
    op.create_index(op.f("ix_user_is_deleted"), "user", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###
